all: esercizio1 esercizio3 gestione_lista

esercizio1:
	gcc -Wall -Wextra -std=c11 esercizio1.c esercizio1_funzioni.c -o esercizio1

# gcc -Wall -Wextra -std=c11 -fno-common esercizio1.c esercizio1_funzioni.c -o esercizio1

esercizio3:
	gcc -Wall -Wextra -std=c11 esercizio3.c esercizio3_contatore.c -o esercizio3

gestione_lista:
	gcc -Wall -Wextra -std=c11 gestione_lista.c -o gestione_lista

clean:
	rm -f esercizio1 esercizio3 gestione_lista
