all: esercizio1 esercizio2 esercizio3 esercizio4 esercizio5 esercizio6 esercizio7 esercizio8 esercizio9 esercizio10

esercizio1:
	gcc -Wall -Wextra -std=c11 esercizio1.c -o esercizio1

esercizio2:
	gcc -Wall -Wextra -std=c11 esercizio2.c -o esercizio2

esercizio3:
	gcc -Wall -Wextra -std=c11 esercizio3.c -o esercizio3

esercizio4:
	gcc -Wall -Wextra -std=c11 esercizio4.c -o esercizio4

esercizio5:
	gcc -Wall -Wextra -std=c11 esercizio5.c -o esercizio5

esercizio6:
	gcc -Wall -Wextra -std=c11 esercizio6.c -o esercizio6

esercizio7:
	gcc -Wall -Wextra -std=c11 esercizio7.c -o esercizio7

esercizio8:
	gcc -Wall -Wextra -std=c11 esercizio8.c -o esercizio8

esercizio9:
	gcc -Wall -Wextra -std=c11 esercizio9.c -o esercizio9

esercizio10:
	gcc -Wall -Wextra -std=c11 esercizio10.c -o esercizio10

clean:
	rm -f esercizio1 esercizio2 esercizio3 esercizio4 esercizio5 esercizio6 esercizio7 esercizio8 esercizio9 esercizio10
