all: esercizio_1 esercizio_2 esercizio_3 esercizio_4 esercizio_5 esercizio_6 esercizio_8 esercizio_9 esercizio_11

esercizio_1:
	gcc -Wall -Wextra "Esercizio 1/esercizio_1.c" -o "Esercizio 1/esercizio_1"

esercizio_2:
	gcc -Wall -Wextra "Esercizio 2/esercizio_2.c" -o "Esercizio 2/esercizio_2"

esercizio_3:
	gcc -Wall -Wextra "Esercizio 3/esercizio_3.c" -o "Esercizio 3/esercizio_3"

esercizio_4:
	gcc -Wall -Wextra "Esercizio 4/esercizio_4.c" -o "Esercizio 4/esercizio_4"

esercizio_5:
	gcc -Wall -Wextra "Esercizio 5/esercizio_5.c" -o "Esercizio 5/esercizio_5"

esercizio_6:
	gcc -Wall -Wextra "Esercizio 6/esercizio_6.c" -o "Esercizio 6/esercizio_6"

esercizio_8:
	gcc -Wall -Wextra "Esercizio 8/esercizio_8.c" -o "Esercizio 8/esercizio_8"

esercizio_9:
	gcc -Wall -Wextra "Esercizio 9/esercizio_9.c" -o "Esercizio 9/esercizio_9"

esercizio_11:
	gcc -Wall -Wextra "Esercizio 11/esercizio_11.c" -o "Esercizio 11/esercizio_11"

clean:
	rm -f "Esercizio 1/esercizio_1" "Esercizio 2/esercizio_2" "Esercizio 3/esercizio_3" \
	      "Esercizio 4/esercizio_4" "Esercizio 5/esercizio_5" "Esercizio 6/esercizio_6" \
	      "Esercizio 8/esercizio_8" "Esercizio 9/esercizio_9" "Esercizio 11/esercizio_11"
