all: esercizio1 esercizio2 esercizio3 esercizio4 esercizio5 esercizio6

esercizio1:
	gcc -Wall -Wextra esercizio1.c -o esercizio1

esercizio2:
	gcc -Wall -Wextra esercizio2.c -o esercizio2

esercizio3:
	gcc -Wall -Wextra esercizio3.c -o esercizio3

esercizio4:
	gcc -Wall -Wextra esercizio4.c -o esercizio4

esercizio5:
	gcc -Wall -Wextra esercizio5.c -o esercizio5

esercizio6:
	gcc -Wall -Wextra esercizio6.c -o esercizio6

clean:
	rm -f esercizio1 esercizio2 esercizio3 esercizio4 esercizio5 esercizio6
