all: esercizio_6 esercizio_7 esercizio_8 esercizio_9

esercizio_6:
	gcc -Wall -Wextra "Esercizio 6/esercizio_6.c" -o "Esercizio 6/esercizio_6"

esercizio_7:
	gcc -Wall -Wextra "Esercizio 7/esercizio_7.c" -o "Esercizio 7/esercizio_7"

esercizio_8:
	gcc -Wall -Wextra "Esercizio 8/esercizio_8.c" -o "Esercizio 8/esercizio_8"

esercizio_9:
	gcc -Wall -Wextra "Esercizio 9/esercizio_9.c" -o "Esercizio 9/esercizio_9"

clean:
	rm -f "Esercizio 6/esercizio_6" "Esercizio 7/esercizio_7" \
	      "Esercizio 8/esercizio_8" "Esercizio 9/esercizio_9"
