all: esercizio_operatori esercizio_1_max2 esercizio_2_divmod esercizio_3_array

esercizio_operatori:
	gcc -Wall -Wextra esercizio_operatori_soluzione.c -o esercizio_operatori_soluzione

esercizio_1_max2:
	gcc -Wall -Wextra esercizio_1_max2_soluzione.c -o esercizio_1_max2_soluzione

esercizio_2_divmod:
	gcc -Wall -Wextra esercizio_2_divmod_soluzione.c -o esercizio_2_divmod_soluzione

esercizio_3_array:
	gcc -Wall -Wextra esercizio_3_array_soluzione.c -o esercizio_3_array_soluzione

clean:
	rm -f esercizio_operatori_soluzione esercizio_1_max2_soluzione esercizio_2_divmod_soluzione esercizio_3_array_soluzione
